### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by Mec-iS** [HTTP-APIs/documentation-hydrus#3]
`README.md` should provide information about how the repo has been developed and which design choices have been made.

**Comment by nityanandagohain** [comment]
@Mec-iS  I want to work on this but I am completely new in this regard . If some help is provided i can definitely do it.

**Comment by Mec-iS** [comment]
Take a look at how the documentation has been built, and write a README that explains how to rebuild it and which parameters has to be set. Start from the creation of a Python virtual environment and a `requirements.txt` with the needed dependencies.
