### ISSUE TITLE
module not found error

### ISSUE THREAD

**Issue by nityanandagohain** [HTTP-APIs/documentation-hydrus#4]
I am trying to build the documentation. This is the error that I am getting.

![screenshot from 2018-02-16 15-15-15](https://user-images.githubusercontent.com/26831659/36302025-e4de278c-132c-11e8-81e6-c3da1744d95a.png)

I have installed hydrus by cd into hydrus folder and then ```pip install -e  .```

**Comment by nityanandagohain** [comment]
ping @sandeepsajan0

**Comment by sandeepsajan0** [comment]
you can do a work that copy-pastes the doc folder in your hydrus repo from documentation-hydrus repo and then run these commands it will work.
Its reason is we have documentation of hydrus repo.

**Comment by sandeepsajan0** [comment]
please tell me, In which repo you are working now?

**Comment by nityanandagohain** [comment]
in hydrus i have copied doc from documentation-hydrus to hydrus

**Comment by sandeepsajan0** [comment]
then open rst folder and run 
 `sphinx-build -b html path/to/rst  path/to/_build/html

**Comment by sandeepsajan0** [comment]
@nityanandagohain  I should be close
